package com.uniubi.devicegateway.command;
public enum CommandType { LED_TEXT_SET, LED_SWITCH, VOICE_CONTENT_SET, VOICE_PLAY, VOICE_STOP, VOICE_VOLUME_SET, VOICE_SWITCH, LAMP_SWITCH, COMPONENT_CONTROL, DEVICE_STATUS_QUERY }
